from ...abstasks.AbsTaskSTS import AbsTaskSTS


class InstructSTSBenchmark(AbsTaskSTS):
    @property
    def description(self):
        return {
            "name": "InstructSTSBenchmark",
            # "data_path": "InstructEmbedBench/results/stsb-gpt-4-stsb_discriminate_v1_converted.json",
            "hf_hub_name": "BrandonZYW/InstructSTSB",
            "revision": "34dda81eca082ba6b3a259899fe9ae435b6ea1ae",
            "description": "Semantic Textual Similarity Benchmark (STSbenchmark) dataset with instructions generated by GPT-4.",
            "reference": "http://ixa2.si.ehu.es/stswiki/index.php/STSbenchmark",
            "type": "STS",
            "category": "s2s",
            "main_score": "cosine_spearman",
            "min_score": 0,
            "max_score": 1,
        }
